steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}',
          '-f', 'praxis/pip_package/release.Dockerfile', '.'
        ]
  timeout: 14400s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}']
  timeout: 1800s
- name: 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'
  entrypoint: 'bash'
  args: ['-c', 'source praxis/pip_package/collect_wheels.sh && collect_wheels ${_RELEASE_VERSION}']

- name: python
  entrypoint: pip
  args: ["install", "twine keyrings.google-artifactregistry-auth", "--user"]
- name: python
  entrypoint: python
  args:
  - '-m'
  - 'twine'
  - 'upload'
  - '--repository-url'
  - 'testpypi'
  - 'praxis-*.whl'

substitutions:
    _PYTHON_VERSION: '3.8'
    _RELEASE_VERSION: '0.2.0'  # or rX.Y
    _IMAGE_NAME: 'praxis_${_RELEASE_VERSION}_${_PYTHON_VERSION}'
options:
    dynamic_substitutions: true
    substitution_option: 'ALLOW_LOOSE'
timeout: 24000s
